name: auto fuck nco jzgsu

on:
  push:
  gollum:
   schedule:
     - cron: '10 0,16 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requirements'
        run: pip3 install -r requirements.txt

      - name: 'Working'
        env:
          users: ${{ secrets.users }}
          api: ${{ secrets.api }}
        run: python3 main.py
